import type { UnifiedReviewFeedPayload } from "../src/types"

export function buildUnifiedReviewFeedPayload(): UnifiedReviewFeedPayload {
  return {
    schema_version: "storage-v2/unified-review-feed@2",
    available: true,
    filters: {
      limit: 100,
      offset: 0,
    },
    total: 4,
    items: [
      {
        id: "archive:CASE_001",
        source: "archive",
        title: "STAT · open-case",
        state_label: "열림",
        reason_label: "latest candidate",
        timestamp: "2026-07-24T12:00:00+09:00",
        meta_label: "capture 2 · revision 3",
        href: "#review/archive/CASE_001",
      },
      {
        id: "timetable:7",
        source: "timetable",
        title: "자료구조 5교시",
        state_label: "검토 대기",
        reason_label: "유일 시간 일치",
        timestamp: "2026-07-24T13:30:00+09:00",
        meta_label: "rec_shared",
        href: "#review/timetable/7",
      },
      {
        id: "title:11",
        source: "title",
        title: "2026-07-24 자료구조 5교시",
        state_label: "검토 대기",
        reason_label: "시간표·전사 내용 일치",
        timestamp: "2026-07-24T13:00:00+09:00",
        meta_label: "rec_shared · transcript r2",
        href: "#review/title/11",
      },
      {
        id: "recording:rec_001",
        source: "recording",
        title: "회의 메모",
        state_label: "열린 검토 1건",
        reason_label: "recording summary 기준 남은 review",
        timestamp: "2026-07-24T11:00:00+09:00",
        meta_label: "rec_001 · 원본 1건",
        href: "#review/recording/rec_001",
      },
    ],
    sources: [
      {
        source: "archive",
        label: "archive",
        status: "ready",
        available: true,
        visible_count: 1,
        total_count: 1,
        truncated: false,
        note: "archive actionable 1건",
        error: null,
      },
      {
        source: "timetable",
        label: "classification",
        status: "ready",
        available: true,
        visible_count: 1,
        total_count: 1,
        truncated: false,
        note: "suggested 1건",
        error: null,
      },
      {
        source: "title",
        label: "title",
        status: "ready",
        available: true,
        visible_count: 1,
        total_count: 1,
        truncated: false,
        note: "title suggested 1건",
        error: null,
      },
      {
        source: "recording",
        label: "recording",
        status: "ready",
        available: true,
        visible_count: 1,
        total_count: 1,
        truncated: false,
        note: "visible review 1건",
        error: null,
      },
    ],
  }
}
